// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const getRoom = `-- name: GetRoom :one
SELECT id, email, name, password FROM users
`

func (q *Queries) GetRoom(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getRoom)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
	)
	return i, err
}
