// Code generated by MockGen. DO NOT EDIT.
// Source: task_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	taskdomain "github.com/Giovani-Coelho/Doti-API/internal/core/domain/task"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CheckExists mocks base method.
func (m *MockTaskRepository) CheckExists(ctx context.Context, taskId int32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExists", ctx, taskId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExists indicates an expected call of CheckExists.
func (mr *MockTaskRepositoryMockRecorder) CheckExists(ctx, taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExists", reflect.TypeOf((*MockTaskRepository)(nil).CheckExists), ctx, taskId)
}

// Create mocks base method.
func (m *MockTaskRepository) Create(ctx context.Context, task taskdomain.Task) (taskdomain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(taskdomain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), ctx, task)
}

// Delete mocks base method.
func (m *MockTaskRepository) Delete(ctx context.Context, taskId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, taskId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepositoryMockRecorder) Delete(ctx, taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepository)(nil).Delete), ctx, taskId)
}

// FindById mocks base method.
func (m *MockTaskRepository) FindById(ctx context.Context, taskId int32) (taskdomain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, taskId)
	ret0, _ := ret[0].(taskdomain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockTaskRepositoryMockRecorder) FindById(ctx, taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockTaskRepository)(nil).FindById), ctx, taskId)
}

// FindOwnerIdByTaskId mocks base method.
func (m *MockTaskRepository) FindOwnerIdByTaskId(ctx context.Context, taskId int32) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOwnerIdByTaskId", ctx, taskId)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOwnerIdByTaskId indicates an expected call of FindOwnerIdByTaskId.
func (mr *MockTaskRepositoryMockRecorder) FindOwnerIdByTaskId(ctx, taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOwnerIdByTaskId", reflect.TypeOf((*MockTaskRepository)(nil).FindOwnerIdByTaskId), ctx, taskId)
}

// ListByModuleId mocks base method.
func (m *MockTaskRepository) ListByModuleId(ctx context.Context, moduleId int32) ([]taskdomain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByModuleId", ctx, moduleId)
	ret0, _ := ret[0].([]taskdomain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByModuleId indicates an expected call of ListByModuleId.
func (mr *MockTaskRepositoryMockRecorder) ListByModuleId(ctx, moduleId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByModuleId", reflect.TypeOf((*MockTaskRepository)(nil).ListByModuleId), ctx, moduleId)
}

// PositionExists mocks base method.
func (m *MockTaskRepository) PositionExists(ctx context.Context, moduleId, position int32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PositionExists", ctx, moduleId, position)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PositionExists indicates an expected call of PositionExists.
func (mr *MockTaskRepositoryMockRecorder) PositionExists(ctx, moduleId, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PositionExists", reflect.TypeOf((*MockTaskRepository)(nil).PositionExists), ctx, moduleId, position)
}

// UpdateCompletion mocks base method.
func (m *MockTaskRepository) UpdateCompletion(ctx context.Context, taskId int32, isComplete bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompletion", ctx, taskId, isComplete)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCompletion indicates an expected call of UpdateCompletion.
func (mr *MockTaskRepositoryMockRecorder) UpdateCompletion(ctx, taskId, isComplete interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompletion", reflect.TypeOf((*MockTaskRepository)(nil).UpdateCompletion), ctx, taskId, isComplete)
}

// UpdateName mocks base method.
func (m *MockTaskRepository) UpdateName(ctx context.Context, taskId int32, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, taskId, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockTaskRepositoryMockRecorder) UpdateName(ctx, taskId, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockTaskRepository)(nil).UpdateName), ctx, taskId, name)
}

// UpdatePosition mocks base method.
func (m *MockTaskRepository) UpdatePosition(ctx context.Context, tasks []taskdomain.TaskPositionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", ctx, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockTaskRepositoryMockRecorder) UpdatePosition(ctx, tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockTaskRepository)(nil).UpdatePosition), ctx, tasks)
}
