// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Module struct {
	ID        int32     `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	IsOpen    bool      `json:"is_open"`
	Icon      string    `json:"icon"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Task struct {
	ID          int32     `json:"id"`
	ModuleID    int32     `json:"module_id"`
	Name        string    `json:"name"`
	IsCompleted bool      `json:"is_completed"`
	Position    int32     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TaskDetail struct {
	ID             int32          `json:"id"`
	TaskID         int32          `json:"task_id"`
	Description    sql.NullString `json:"description"`
	PomodoroTarget sql.NullInt32  `json:"pomodoro_target"`
	PomodoroSpent  sql.NullInt32  `json:"pomodoro_spent"`
	ActualTime     sql.NullInt32  `json:"actual_time"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Password  string         `json:"password"`
	IsAdmin   bool           `json:"is_admin"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
