// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_details_query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTaskDetails = `-- name: CreateTaskDetails :exec
INSERT INTO task_details (task_id, description)
VALUES ($1, $2)
`

type CreateTaskDetailsParams struct {
	TaskID      int32          `json:"task_id"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateTaskDetails(ctx context.Context, arg CreateTaskDetailsParams) error {
	_, err := q.db.ExecContext(ctx, createTaskDetails, arg.TaskID, arg.Description)
	return err
}
