// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/app/task/create_task_usecase.go

// Package mock_taskcase is a generated GoMock package.
package mock_taskcase

import (
	context "context"
	reflect "reflect"

	taskdomain "github.com/Giovani-Coelho/Doti-API/internal/core/domain/task"
	gomock "github.com/golang/mock/gomock"
)

// MockCreate is a mock of Create interface.
type MockCreate struct {
	ctrl     *gomock.Controller
	recorder *MockCreateMockRecorder
}

// MockCreateMockRecorder is the mock recorder for MockCreate.
type MockCreateMockRecorder struct {
	mock *MockCreate
}

// NewMockCreate creates a new mock instance.
func NewMockCreate(ctrl *gomock.Controller) *MockCreate {
	mock := &MockCreate{ctrl: ctrl}
	mock.recorder = &MockCreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreate) EXPECT() *MockCreateMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreate) Execute(ctx context.Context, task taskdomain.Task) (taskdomain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, task)
	ret0, _ := ret[0].(taskdomain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateMockRecorder) Execute(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreate)(nil).Execute), ctx, task)
}
